### ISSUE TITLE
links are broken

### ISSUE THREAD

**Issue by supermarin** [tmrts/go-patterns#1]

**Comment by stuartweir** [comment]
which links in particular?

**Comment by andyleap** [comment]
Like, most of them?  Did you even try any?  Literally the first 3 links are all broken, and tons of the rest...

**Comment by rojaster** [comment]
ain't cool

**Comment by Mercede5** [comment]
show me the code!!!!!!!!

**Comment by mrichman** [comment]
Github links broken. Website links broken.

**Comment by santacruz123** [comment]
I thought it's work in progress

**Comment by stuartweir** [comment]
All I saw was the different repos (not part of this project), but yeah you're right, all the site links are 404's.

**Comment by tmrts** [comment]
Thank you all for showing interest in the repository, however I am a bit upset that this was posted in HN, this was a WIP I tinkered on my free time so its far from perfect. However, I'll focus on the issues in the repository for the next couple of days so hang on tight 😄

**Comment by tmrts** [comment]
**Update:** http://tmrts.com/go-patterns no longer has broken links, and a few more patterns, more updates to come!

**Comment by supermarin** [comment]
still broken.

**Comment by tmrts** [comment]
@supermarin do you mean the incomplete patterns or is there a broken link in the implemented patterns? if former, maybe we can remove the incomplete ones for now

**Comment by tmrts** [comment]
I've arranged the repository to fix the broken links and added indication to unfinished patterns, feel free to re-open this if there are still problems
