### ISSUE TITLE
go-patterns/messaging/publish_subscribe.md

### ISSUE THREAD

**Issue by cuiyuan** [tmrts/go-patterns#13]
[https://github.com/tmrts/go-patterns/blob/master/messaging/publish_subscribe.md](url)

```go
 if _, ok := s.ch; !ok {
        return errors.New("Topic has been closed")
 }
```

assignment count mismatch: 2 = 1

**Comment by tmrts** [comment]
@cuiyuan good catch! thanks fixed in 82fc76d6ab592a
