### ISSUE TITLE
Circuit breaker is broken, and was copied without credit

### ISSUE THREAD

**Issue by zcspencer** [tmrts/go-patterns#14]
The [circuit breaker](https://github.com/tmrts/go-patterns/blob/master/stability/circuitbreaker.go) example is mostly a copy paste from [sony/gobreaker/gobreaker.go](https://github.com/sony/gobreaker/blob/master/gobreaker.go) without credit for the original authors. Furthermore, the example doesn't build due to missing constants: `Counts` and `State`.

**Comment by tmrts** [comment]
I'm sorry that this happened, but I haven't seen your repository before

This was an example I took from another repository (which I was hoping to revise). So it might be a third-hand copy, still no excuse for bad behavior of course. 

Please let me know if there is anything I can do to remedy the situation!

**Comment by tmrts** [comment]
I have rewritten the circuit breaker example and I also added a reference to the `sony/gobreaker` implementation at 5895317

Let me know if there is anything I've missed
