### ISSUE TITLE
can you release a pdf file for print

### ISSUE THREAD

**Issue by wjx0912** [tmrts/go-patterns#46]
thanks.

**Comment by garrickjubiao** [comment]
agree more

**Comment by kifirkin** [comment]
@wjx0912 @garrickjubiao you can generate it with `gitbook-cli` but there some problems:
1. Badges in `README.MD` produces `file not found` gitbook error
1. `*.go` files better include in corresponding `*.md` files
1. Update `book.json` with `author`, `title`, etc.
