### ISSUE TITLE
Use buffered channel instead of list.List in object pool example?

### ISSUE THREAD

**Issue by ammario** [tmrts/go-patterns#8]
Instead of a list, using channels and `select` as demonstrated [here](https://www.reddit.com/r/golang/comments/2ap67l/when_to_use_syncpool_and_when_not_to/cixhc0f) makes for a much more beautiful demonstration.

**Comment by tmrts** [comment]
The goal of this repository to prevent common patterns in a very simple manner and I agree with your assessment, thank you for your suggestion!

**Comment by tmrts** [comment]
I tried to make the object pool as simple as possible here 6a717fe, let me know if you have any thoughts on it
